FROM node:16.13

# The /app directory should act as the main application directory
WORKDIR /usr/src/app
# Copy the app package and package-lock.json file
COPY package*.json ./
# Install node packages
RUN npm install
# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY . .
# Build the app
RUN npm run build
EXPOSE 3000
# Start the app
CMD [ "npm", "run", "start" ]
