version: '3.8'

services:
  dev_api:
    container_name: dikos_api_dev
    image: dikos-api-dev:1.0.0
    env_file:
      - ./backend/.dev.env
    volumes:
      - shared_data:/forecast
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - 6969:6969
      - 9229:9229
    restart: unless-stopped
    depends_on:
      - mongo
      - machine_learning
  machine_learning:
    container_name: machine-learning
    image: dikos-machine-learning:1.0.0
    volumes:
      - shared_data:/forecast
    build:
      context: ./machine_learning
      dockerfile: Dockerfile
    command: python3 main.py
    ports:
      - 4000:4000
    restart: unless-stopped
  mongo:
    image: mongo
    ports:
      - 27017:27017
  prod_api:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    env_file:
      - ./backend/.prod.env
    build:
      context: ./backend
      target: production
      dockerfile: Dockerfile
    command: npm run start:prod
    ports:
      - 6969:6969
      - 9229:9229
    restart: unless-stopped
    depends_on:
      - machine_learning
  dev_ui:
    container_name: dikos_ui_dev
    image: dikos_ui_dev:1.0.0
    environment:
      - API_URL=http://dev_api:6969/
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    restart: unless-stopped
  prod_ui:
    container_name: dikos_ui_prod
    image: dikos_ui_prod:1.0.0
    environment:
      - API_URL=http://prod_api:6969/
    build:
      context: ./frontend
      target: production
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  shared_data: