# version: '3.8'

# services:
#     dev_api:
#         container_name: nestjs_api_dev
#         image: nestjs-api-dev:1.0.0
#         build:
#             context: .
#             target: development
#             dockerfile: ./backend/Dockerfile
#         command: npm run start:debug
#         ports:
#             - ${PORT}:${PORT}
#             - 9229:9229
#         networks:
#             - nesjs-network
#         volumes:
#             - .:/usr/src/app
#             - /usr/src/app/node_modules
#         restart: unless-stopped
#     prod_api:
#         container_name: nestjs_api_prod
#         image: nestjs-api-prod:1.0.0
#         build:
#             context: .
#             target: production
#             dockerfile: ./backend/Dockerfile
#         command: npm run start:prod
#         ports:
#             - ${PORT}:${PORT}
#             - 9229:9229
#         networks:
#             - nesjs-network
#         volumes:
#             - .:/usr/src/app
#             - /usr/src/app/node_modules
#         restart: unless-stopped
#     frontend:
#         container_name: react_front_app
#         image: react_front_app:1.0.0
#         build:
#             context: .
#             target: development
#             dockerfile: ./frontent/Dockerfile
#         command: npm run start
#         ports:
#             - 3000:3000
#             - 9229:9229
#         volumes:
#             - .:/usr/src/frontend
#             - /usr/src/frontend/node_modules
#         restart: unless-stopped

# networks:
#     nesjs-network: