name: Continuous Integration

on:
  pull_request:
    branches: [ master ]


jobs:
  ui_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - run: cd frontend
      - run: npm ci
      - run: npm run build
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - run: cd backend
      - run: npm ci
      - run: npm run build