name: Continuous Integration for backend

on:
  pull_request:
    branches:
      - master
      - bugfix/**
      - feature/**
    paths:
      - './backend/**'
  workflow_dispatch:


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17
      - name: Build backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build